[workspace]
members = [
  "crates/ispf-core",
  "crates/ispf-command",
  "crates/ispf-screen",
  "crates/ispf-tui",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.2"

[workspace.dependencies]
anyhow = "1.0"
crossterm = "0.28"
insta = "1.43"
ratatui = "0.29"
thiserror = "2.0"
unicode-width = "0.2"
