[package]
name = "ispf-tui"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "pf3-edit"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ispf-command = { path = "../ispf-command" }
ispf-core = { path = "../ispf-core" }
ispf-screen = { path = "../ispf-screen" }
ratatui.workspace = true
